#!/bin/bash

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa

#if [ ! -e ~/.fzf ]; then
#  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
#  ~/.fzf/install
#fi

# if [ ! -e ~/.zplug ]; then
#   curl -sL zplug.sh/installer | zsh
# fi

# if [ ! -e ~/.git-aliae ]; then
#   git clone --depth 1 https://github.com/ConradIrwin/git-aliae.git ~/.git-aliae
# fi

if [ ! -e ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
